server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sep
            client-secret: 7S8kHyEdLdEePmrzg19BRE9LIuAovH9O
            client-name: Keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/sep/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/sep/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/sep/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:8080/realms/sep/protocol/openid-connect/certs
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/sep/protocol/openid-connect/certs